version: '3'

volumes:
  kc_postgres:

services:
  kc_db:
    image: postgres
    volumes:
      - kc_postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
  backend:
    build: ./usetech/
    volumes:
      - ./usetech:/app
    ports:
      - 8001:8000
  gateway:
    build: ./nginx/
    depends_on:
      - backend
    ports:
      - 8000:80
  keycloak:
    image: quay.io/keycloak/keycloak:22.0.3
    command: start-dev
    env_file: .env
    ports:
      - 8080:8080
    depends_on:
      - kc_db
